### ISSUE TITLE
Automatic upgrade is not working

### ISSUE THREAD

**Issue by ssharma2089** [PyratLabs/ansible-role-k3s#35]
I have tried to automate k3s upgrade from 1.17.5+k3s1 to 1.17.6+k3s1 by using system-upgrade-controller but it's not upgrading.

I have referred the below link to upgrade k3s and followed step by step
[https://github.com/rancher/k3s-upgrade](url)

I have raised the same issue in rancher/system-upgrade-controller. Issue - [https://github.com/rancher/system-upgrade-controller/issues/90](url)

After debugging, I got to know that  the plan is looking for name k3s in /usr/local/bin however while installing from playbook it's installed as k3s- version (k3s-v1.17.5+k3s1). Because of this, I am getting an error "/host/usr/local/bin/k3s': No such file or directory".

Can you please suggest, what will be the best way to automate upgrade plan.

**Comment by xanmanning** [comment]
Hi @ssharma2089 

The automated upgrade using system-upgrade-controller was introduced in K3S v1.17.4+k3s1 in March 2020: https://rancher.com/docs/k3s/latest/en/upgrades/automated/

When this role was written the method for upgrade was as per the below, which is effectively automated by re-running this role:
https://rancher.com/docs/k3s/latest/en/upgrades/basic/

The reason why you will be getting the following error:

> "/host/usr/local/bin/k3s: No such file or directory"

... will be because of how this role installs K3S - it downloads a named version of the binary to `/usr/local/bin` (as `/usr/local/bin/k3s-1.17.5+k3s1` for example) and then creates the following symlinks pointing to that named version:

 - `/usr/local/bin/k3s -> /usr/local/bin/k3s-1.17.5+k3s1`
 - `/usr/local/bin/kubectl -> /usr/local/bin/k3s-1.17.5+k3s1`
 - `/usr/local/bin/ctr -> /usr/local/bin/k3s-1.17.5+k3s1`
 - `/usr/local/bin/crictl -> /usr/local/bin/k3s-1.17.5+k3s1`

From inside your k3s cluster, `/host/usr/local/bin/k3s` will point to somewhere that doesn't exist inside your cluster.

The rationale behind this is that it may be theoretically possible to "roll back" the upgrade, this would be quick running the automation from this role as Ansible wouldn't need to re-download k3s, effectively it would just need to repoint the symlink to the named version.

Given that containers cannot follow symlinks, it may be possible to modify the role to create hard links - the thing is if I were to implement this, it won't be possible (using ansible) to verify the hard link has been set up correctly using `stat`'s `islnk` check: https://docs.ansible.com/ansible/latest/modules/stat_module.html#return-stat/islnk - though I may be able to do it by checking inodes are identical.

I'll have a play but I don't use rancher/system-upgrade-controller yet.

**Comment by xanmanning** [comment]
![Screenshot from 2020-07-25 12-02-00](https://user-images.githubusercontent.com/244186/88455614-a8af3300-ce6e-11ea-913e-785bad59bc6c.png)

I've attempted to change from soft links to hard links and perform an upgrade. It breaks. I'm looking into it further but it may take me a while to work it out as this is a project I do in my limited spare time.

**Comment by xanmanning** [comment]
I think I've managed to resolve the issue above changing soft links to hard links by passing the `force: true` parameter to the `file` module. I suspect this deletes the destination before re-creating it.

```
[root@node1 bin]# ls -larthi | grep -E 'k3s|ctr|ctl' | grep -vE ".sh$" | sort
3277822 -rwxr-xr-x 1 root root  52M Jul 25 10:58 k3s-v1.18.4+k3s1
3279636 -rwxr-xr-x 5 root root  51M Jul 25 11:00 crictl
3279636 -rwxr-xr-x 5 root root  51M Jul 25 11:00 ctr
3279636 -rwxr-xr-x 5 root root  51M Jul 25 11:00 k3s
3279636 -rwxr-xr-x 5 root root  51M Jul 25 11:00 k3s-v1.18.6+k3s1
3279636 -rwxr-xr-x 5 root root  51M Jul 25 11:00 kubectl
```

Please can you test again by cloning this repo in place of the xanmanning.k3s role and checking out the branch `feature-symlink_to_hardlink` ?

**Comment by ssharma2089** [comment]
Hi @xanmanning, 

Thanks for update and fix.
I have tested and confirmed that hardlink feature and system-upgrade plan is working fine,

However, I am getting an error while uninstalling k3s
Below 3 files are not getting removed
-rwxr-xr-x  3 root root 52686848 Jul 25 22:53 crictl*
-rwxr-xr-x  3 root root 52686848 Jul 25 22:53 ctr*
-rwxr-xr-x  3 root root 52686848 Jul 25 22:53 kubectl*

Logs for uninstall:

TASK [xanmanning.k3s : Fail if k3s binaries have not been removed] ***************************************************************************
Saturday 25 July 2020  22:18:41 +0530 (0:00:00.037)       0:00:06.728 ********* 
ok: [192.168. 225.147] => (item=k3s)
failed: [192.168. 225.147] (item=kubectl) => {"ansible_loop_var": "item", "changed": false, "failed_when_result": true, "item": "kubectl", "stat": {"atime": 1595695679.5949163, "attr_flags": "e", "attributes": ["extents"], "block_size": 4096, "blocks": 102912, "charset": "binary", "checksum": "397e6cb19d12c1d7834acb3d6e3de1f8855204cc", "ctime": 1595695721.129813, "dev": 2049, "device_type": 0, "executable": true, "exists": true, "gid": 0, "gr_name": "root", "inode": 2872419, "isblk": false, "ischr": false, "isdir": false, "isfifo": false, "isgid": false, "islnk": false, "isreg": true, "issock": false, "isuid": false, "mimetype": "application/x-executable", "mode": "0755", "mtime": 1595695662.3234184, "nlink": 3, "path": "/usr/local/bin/kubectl", "pw_name": "root", "readable": true, "rgrp": true, "roth": true, "rusr": true, "size": 52686848, "uid": 0, "version": "3420098775", "wgrp": false, "woth": false, "writeable": true, "wusr": true, "xgrp": true, "xoth": true, "xusr": true}}
failed: [192.168. 225.147] (item=crictl) => {"ansible_loop_var": "item", "changed": false, "failed_when_result": true, "item": "crictl", "stat": {"atime": 1595695721.9937916, "attr_flags": "e", "attributes": ["extents"], "block_size": 4096, "blocks": 102912, "charset": "binary", "checksum": "397e6cb19d12c1d7834acb3d6e3de1f8855204cc", "ctime": 1595695721.129813, "dev": 2049, "device_type": 0, "executable": true, "exists": true, "gid": 0, "gr_name": "root", "inode": 2872419, "isblk": false, "ischr": false, "isdir": false, "isfifo": false, "isgid": false, "islnk": false, "isreg": true, "issock": false, "isuid": false, "mimetype": "application/x-executable", "mode": "0755", "mtime": 1595695662.3234184, "nlink": 3, "path": "/usr/local/bin/crictl", "pw_name": "root", "readable": true, "rgrp": true, "roth": true, "rusr": true, "size": 52686848, "uid": 0, "version": "3420098775", "wgrp": false, "woth": false, "writeable": true, "wusr": true, "xgrp": true, "xoth": true, "xusr": true}}
failed: [192.168. 225.147] (item=ctr) => {"ansible_loop_var": "item", "changed": false, "failed_when_result": true, "item": "ctr", "stat": {"atime": 1595695721.9937916, "attr_flags": "e", "attributes": ["extents"], "block_size": 4096, "blocks": 102912, "charset": "binary", "checksum": "397e6cb19d12c1d7834acb3d6e3de1f8855204cc", "ctime": 1595695721.129813, "dev": 2049, "device_type": 0, "executable": true, "exists": true, "gid": 0, "gr_name": "root", "inode": 2872419, "isblk": false, "ischr": false, "isdir": false, "isfifo": false, "isgid": false, "islnk": false, "isreg": true, "issock": false, "isuid": false, "mimetype": "application/x-executable", "mode": "0755", "mtime": 1595695662.3234184, "nlink": 3, "path": "/usr/local/bin/ctr", "pw_name": "root", "readable": true, "rgrp": true, "roth": true, "rusr": true, "size": 52686848, "uid": 0, "version": "3420098775", "wgrp": false, "woth": false, "writeable": true, "wusr": true, "xgrp": true, "xoth": true, "xusr": true}}

Verbose mode :

failed: [192.168. 225.147] (item=kubectl) => {
    "ansible_loop_var": "item", 
    "changed": false, 
    "failed_when_result": true, 
    "invocation": {
        "module_args": {
            "checksum_algorithm": "sha1", 
            "follow": false, 
            "get_attributes": true, 
            "get_checksum": true, 
            "get_md5": false, 
            "get_mime": true, 
            "path": "/usr/local/bin/kubectl"
        }
    }, 
    "item": "kubectl", 
    "stat": {
        "atime": 1595696559.7823336, 
        "attr_flags": "e", 
        "attributes": [
            "extents"
        ], 
        "block_size": 4096, 
        "blocks": 102904, 
        "charset": "binary", 
        "checksum": "397e6cb19d12c1d7834acb3d6e3de1f8855204cc", 
        "ctime": 1595696558.9823272, 
        "dev": 2049, 
        "device_type": 0, 
        "executable": true, 
        "exists": true, 
        "gid": 0, 
        "gr_name": "root", 
        "inode": 2872420, 
        "isblk": false, 
        "ischr": false, 
        "isdir": false, 
        "isfifo": false, 
        "isgid": false, 
        "islnk": false, 
        "isreg": true, 
        "issock": false, 
        "isuid": false, 
        "mimetype": "application/x-executable", 
        "mode": "0755", 
        "mtime": 1595696043.6651864, 
        "nlink": 3, 
        "path": "/usr/local/bin/kubectl", 
        "pw_name": "root", 
        "readable": true, 
        "rgrp": true, 
        "roth": true, 
        "rusr": true, 
        "size": 52686848, 
        "uid": 0, 
        "version": "2608551931", 
        "wgrp": false, 
        "woth": false, 
        "writeable": true, 
        "wusr": true, 
        "xgrp": true, 
        "xoth": true, 
        "xusr": true
    }
}

**Comment by xanmanning** [comment]
Hi @ssharma2089 - Can you try again? I've pushed an update to k3s-uninstall.sh script.

**Comment by xanmanning** [comment]
Hi @ssharma2089, just to let you know I have released [v1.9.0](https://github.com/PyratLabs/ansible-role-k3s/tree/v1.9.0) of this role, in order to maintain backwards compatibility you will need to set the following parameter to use hard links rather than symbolic links:

`k3s_install_hard_links: true`

This should be on [ansible-galaxy](https://galaxy.ansible.com/xanmanning/k3s) within an hour of me posting this.

**Comment by ssharma2089** [comment]
Thanks for the quickly fix. I have checked and it's working fine.

**Comment by xanmanning** [comment]
Fantastic, thanks for checking :) :+1:
