### ISSUE TITLE
Drop Docker support(?)

### ISSUE THREAD

**Issue by xanmanning** [PyratLabs/ansible-role-k3s#67]
### Summary

The Kubernetes team are going to deprecate support for Docker after v1.20, this is likely to get filtered down into the k3s distribution. Installation of Docker has been handled by this role, however I have always debated whether or not this should be handled by another, external role (eg. Write my own or use geerlingguy.docker, or whatever).

Removal of docker support should come with documentation providing information about using alternative container runtimes

### Issue Type

- Feature Request

### User Story

_As a_ developer \
_I want_ guidance on container runtimes \
_So that_ I can run my application on K3s using a supported method.

### Additional Information

- https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/
- https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#deprecation
- https://rancher.com/docs/k3s/latest/en/installation/install-options/agent-config/#runtime
- https://github.com/k3s-io/k3s/issues/2622
- https://support.rancher.com/hc/en-us/articles/360053308831
- https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/1985-remove-dockershim

**Comment by eamonryan** [comment]
It seems logical that if k3s itself drops support for Docker, there's no reason to support it here.

That said, I currently run Docker in my deployment due to hitting [this issue](https://github.com/k3s-io/k3s/issues/924) some time ago and swapping to Docker from containerd got me around that.

Do you know if k3s auto detects in that scenario? Or is it a setting that should be exposed via this Ansible role to let users choose?

Additionally, if dropping Docker support, it'd be great to have guidance on how to migrate - whether the role can cleanly migrate or what kind of intervention is required.

**Comment by xanmanning** [comment]
I believe k3s will be moving in line with Kubernetes as per [Rancher's official statement](https://support.rancher.com/hc/en-us/articles/360053308831) so for k3s v1.20 there will be a deprecation warning and by v1.21 dockershim will most likely be completely removed. Whether or not k3s will attach a link to documentation in this deprecation warning to provide guides for swapping out Docker for containerd (or cri-o) I'm not sure, it would be tremendously helpful if it did.

This Ansible role gives you the option to use Docker but I have already now released a check that will fail when you get to v1.20 of k3s if you specify the use of Docker. You will need to then supply the `k3s_use_unsupported_config: true` to get past this error. I was in the process of extending these checks so that I can attach links to documentation in the fail message, this hasn't been released yet as I am in the process of creating documentation for using this role so I don't have a lot to reference.

I am keen to try and guide users of this role as best I can with the execution of this code, this is why I want to spend a lot of time building in checks (see `tasks/validation/` directory). I'm not sure yet if I will provide automation to help people migrate off of Docker. I appreciate the process appears to be one-by-one drain worker nodes, change config to containerd, uncordon the worker nodes and allow containers to be re-created, however there are likely a load of edge cases that I cannot account for so this presents risk. I might be more inclined to detect if Docker is present on target servers and provide links to documentation for manual intervention.

As a glimmer of hope for some, I think I saw somewhere that there may be a third-party development for dockershim which can be installed post Kubernetes installation to continue docker support past v1.21, but I can't find sources for this and I don't know how it would fit in with k3s. If I find where I saw this I will add it to this post in an edit.

**Comment by eamonryan** [comment]
> I believe k3s will be moving in line with Kubernetes as per [Rancher's official statement](https://support.rancher.com/hc/en-us/articles/360053308831) so for k3s v1.20 there will be a deprecation warning and by v1.21 dockershim will most likely be completely removed. Whether or not k3s will attach a link to documentation in this deprecation warning to provide guides for swapping out Docker for containerd (or cri-o) I'm not sure, it would be tremendously helpful if it did.

Absolutely, I hope this is the case, especially since I'll have an awkward time in my own cluster otherwise :)

> This Ansible role gives you the option to use Docker but I have already now released a check that will fail when you get to v1.20 of k3s if you specify the use of Docker. You will need to then supply the `k3s_use_unsupported_config: true` to get past this error. I was in the process of extending these checks so that I can attach links to documentation in the fail message, this hasn't been released yet as I am in the process of creating documentation for using this role so I don't have a lot to reference.

I did see that that check was added. Good call. Admittedly I'm personally on an older (1.18) version at the moment but I'd like to move up to latest when the docker migration path is more clear.

> I am keen to try and guide users of this role as best I can with the execution of this code, this is why I want to spend a lot of time building in checks (see `tasks/validation/` directory). I'm not sure yet if I will provide automation to help people migrate off of Docker. 

It would be pretty amazing if the role could handle the migration (and subsequent cleanup) off Docker, but I can definitely understand that is no small task.

> I appreciate the process appears to be one-by-one drain worker nodes, change config to containerd, uncordon the worker nodes and allow containers to be re-created, however there are likely a load of edge cases that I cannot account for so this presents risk. I might be more inclined to detect if Docker is present on target servers and provide links to documentation for manual intervention.

At a glance that doesn't sound _*too*_ bad but I agree there is still plenty of room for weird cases and rollback may prove difficult. Maybe some automation combined with a "if it falls apart" FAQ page that is added to over time would help, as new edge cases are found.

> As a glimmer of hope for some, I think I saw somewhere that there may be a third-party development for dockershim which can be installed post Kubelet installation to continue docker support past v1.21, but I can't find sources for this and I don't know how it would fit in with k3s. If I find where I saw this I will add it to this post in an edit.
> 
> **Edit**: Looks like Mirantis and Docker will be continuing the development of dockershim. https://www.mirantis.com/blog/mirantis-to-take-over-support-of-kubernetes-dockershim-2/

> I've not tested this and I have never used this, but there is an option for specifying a [Contrainer Runtime Endpoint](https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/#agent-runtime) which you'll probably need to point to whatever is released by Mirantis/Docker/whoever.

I did hear about this, reading the blog post more closely it looks like it would still be a tradeout of the in-built (and to-be-removed) dockershim with the Mirantis supported one, which potentially could introduce new problems too, though I'd guess the odds are lower since it is meant to just be a follow on of the same code.

Personally I'd be happy to just move back to containerd if the path was clear, as mentioned before I only went the Docker route to get around that snapshotter issue, which seems to be now selectable as a k3s argument, though I'm not sure if there is any auto-detect code in there now (in k3s or containerd) or if it's a setting that would need to be exposed in the role to make it a choice.
