### ISSUE TITLE
How to upgrade a cluster deployed with ansible-role-k3s playbook?

### ISSUE THREAD

**Issue by ieugen** [PyratLabs/ansible-role-k3s#83]
Hi,

I've deployed a cluster with this ansible playbook and I would like to upgrade it to a patch version of kubernetes.
It's not clear to me how can I do that.

Can you share some the list of steps that I need to do? 
I can try them out and add them to the documentation. 

I've also noticed the documentation does not cover this steps https://github.com/PyratLabs/ansible-role-k3s/tree/main/documentation . 

p.s. I'm using version 1.17.4  of this playbook.

**Comment by ieugen** [comment]
I would also like to mention that I'm using ansible 2.9 (which comes with Debian Stable and Ubuntu 20.04).
This limits my ability to adopt version 2.x of this project.

I don't think I would upgrade to 2.10 until it reaches the Debian repositories.
One of the reasons is that I'm not familiar with python ecosystem to take that part on.

https://tracker.debian.org/pkg/ansible 
https://packages.ubuntu.com/focal/ansible 

I manage multiple servers and it's very costly when I have to maintain/install software outside the main repo - and I try to avoid getting into these situations. 
I'm mentioning this since I'm probably not the only one.

Perhaps you would take this into consideration when deciding the baseline ansible version (and other packages).
This was meant to be of help for you.

Thank you for working on this.

Regards,

**Comment by xanmanning** [comment]
> I manage multiple servers and it's very costly when I have to maintain/install software outside the main repo

How many Ansible controllers do you have?

Yes this is a piece of documentation I'm yet to write.

Upgrade should be possible by changing `k3s_release_version` to your desired version. The controllers (servers) are updated first then nodes (workers) are updated second, see below:

https://rancher.com/docs/k3s/latest/en/upgrades/basic/

v2.x may work with 2.9 in practice more, but some FQCNs were buggy when I last attempted it some months ago (eg. `set_fact`). I'll investigate but I can't commit to a timeline.

**Comment by xanmanning** [comment]
Hi @ieugen 

Because of [this bug](https://github.com/ansible/ansible/pull/72958) the minimum 2.9 ansible version supported is 2.9.17. Below is the error received for any versions below 2.9.17 (tested on 2.9.16):

![Screenshot from 2021-01-24 12-07-42](https://user-images.githubusercontent.com/244186/105629773-ec462200-5e3c-11eb-8c6f-b386f3406eb5.png)

This is because I have moved on to using FQCNs as I may start adding specific module collections to interact with k3s (for example the `community.kubernetes` collection) and I want to ensure the correct collection is being addressed. The Debian repo you pointed out will allow this version to be installed, but your Ubuntu repos are behind.

These requirements can be met by installing Ansible with `pip`

https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#installing-ansible-with-pip

If you need an Ansible role to install Ansible with `pip`, then check out [`geerlingguy.ansible`](https://github.com/geerlingguy/ansible-role-ansible)

> I manage multiple servers and it's very costly when I have to maintain/install software outside the main repo - and I try to avoid getting into these situations.

After all, what is Ansible for if not to reduce the cost and remove the pain of managing systems :wink: 

I am working on changing my requirements.txt, the ansible check and updating the documentation for doing K3s updates.

**Comment by ieugen** [comment]
Thank you very much @xanmanning for taking the time and considering this issue.
I'm on 2.9.16 so I will have to upgrade and instruct the others to do the same.

Have a great day,
Eugen
